title: Zeki Kazan # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a fifth-year Ph.D. candidate in statistical science at Duke University, advised
  by Dr. Jerry Reiter.
  My research interests are at the intersection of differential privacy, Bayesian
  methods, disclosure risk assessment, and applications to social science data.
  <br><br>
  My research career began at Reed College, where I conducted two summer research projects. 
  During my Ph.D., in addition to my disstertation research,
  I conducted a research project as an intern at TikTok in the summer of 2024.
  I plan to defend my dissertation in March 2025. 
  <br><br>
  In 2024, I was appointed Students/Young Professionals Chair for the ASA Privacy 
  and Confidentiality Interest Group.
  I have also served as a reviewer for the Journal of Privacy and Confidentiality,
  Harvard Data Science Review, and the International Conference in Machine Learning.
  <br><br>
  <a href="https://www.linkedin.com/in/zeki-kazan-2627a5155/">LinkedIn</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=IURUXKYAAAAJ">Google Scholar</a> 
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
